### ISSUE TITLE
README screenshot broken

### ISSUE THREAD

**Issue by markwylde** [btd/esbuild-visualizer#2]
Thank you for this library. It's amazing and helped me a lot. Clean, simply and lightening fast.

Just making this issue mostly to say thanks, but also to report that the screenshot is broken on the README.

**Comment by btd** [comment]
@markwylde thanks for the kind words. I do not want to invest too much time as esbuild quite frequently changing format of metadata. Most of the work i copied from my rollup-plugin-visualizer. Periodically i will sync them in some way or another maybe copying other charts also. But first i would like esbuild become more stable before investing more free time to it.

**Comment by iambumblehead** [comment]
There does not appear to be a screenshot at the README. A screenshot would be excellent
