### ISSUE TITLE
export visualizer

### ISSUE THREAD

**Issue by unional** [btd/esbuild-visualizer#4]
Would you be open to export the `visualizer` so that it can be used programmatically?

I'm trying to work on this issue: https://github.com/ai/size-limit/issues/302
and maybe deep linking to `require('esbuild-visualizer/dist/plugin')` is not a good idea.

**Comment by btd** [comment]
Hi. So we just need to add main entry to package json. Do you want to add it?

**Comment by btd** [comment]
I also just read issue you linked. In rollup-plugin-visualizer i added some time ago text templates (for commiting to git). By idea we can set for example for filename to be `stdout`to make it possible to output to stdout

**Comment by unional** [comment]
thanks. Sure, I can make a PR.

For the text output, I have tried the `@size-limit/webpack-why`, it will show the html in a browser, so I can probably do the same using `http-server` or something.

I have not tried the other options in `@size-limit/webpack-why` like `--save-bundle` yet. Will see how that behaves and see if we want to bring parity on that.

**Comment by btd** [comment]
It is not necessary to have http server. You can use `open` to open html file in default user agent.
