### ISSUE TITLE
Read multiple metafiles for one report

### ISSUE THREAD

**Issue by justarandomgeek** [btd/esbuild-visualizer#6]
I'm working on a VSCode extension which requires a split esbuild config for the main extension bundle and for the webview bundles, which results in two separate metafiles from esbuild. It would be nice to be able to specify both in `--metadata` and have the chart show all the bundles at once.

**Comment by btd** [comment]
Hi. Thanks for feedback. I do not have time to implement this any time
soon. I can give you guidance if you ok doing pr.
In rollup plugin in cli there is a merge functionality. You can process
metadata to internal representation, merge them and continue process

вт, 24 янв. 2023 г., 18:55 justarandomgeek ***@***.***>:

**Comment by btd** [comment]
In 0.5.0 `--metadata` can be repeated multiple times
