### ISSUE TITLE
How does the resync with rollup-plugin-visualizer work? 

### ISSUE THREAD

**Issue by rehanvdm** [btd/esbuild-visualizer#7]
The usage of the visualizer [here](https://github.com/btd/esbuild-visualizer/blob/master/bin/cli.ts#L58) does not seem to match with the most recent rollup-plugin-visualizer definition [here](https://github.com/btd/rollup-plugin-visualizer/blob/master/plugin/index.ts#L133) 
```
  const fileContent = await visualizer(jsonContent, {
    title: args.title,
    template: args.template,
  });
```

Am I correct in assuming that you change this file to work with the esbuild every time you do the "resync with the rollup plugin"?

Is this package stable enough? And will it be updated every now and then with the rollup to stay in sync? 

Reasons for asking is that I want to use it a CDK construct to analyze the bundle after it builds with esbuild. Also thinking of writing a blog post and just generally getting the word out there about this visualizer. 

Thanks for your work on this 🙌

**Comment by btd** [comment]
Hi

> Am I correct in assuming that you change this file to work with the esbuild every time you do the "resync with the rollup plugin"?

Frontend files usually copied as is. Backend has some small changes. CLI in both projects are custom.

> Is this package stable enough? And will it be updated every now and then with the rollup to stay in sync?

It is as stable as you can see it now. I can only guarantee that i am updating this to match changes to manifest file of esbuild. It is open source and see license about guarantee in general (there is no). Open source is about trust. You either trust me as maintainer or not - basically do your own judgement.

**Comment by rehanvdm** [comment]
Appreciate the reply, sorry I should have also phrased my question a bit better.

> Frontend files usually copied as is. Backend has some small changes. CLI in both projects are custom.

I was looking for this as a script in the repo but could not find how you are doing it, so I assumed it was being done manually. Is there anyway that it can be automated? Or at least put it into a script that can just be ran?

**Comment by btd** [comment]
Yes. Current approach is manual. There are only 4-5 files that are different. When i first wrote this version i made huge portion of plugin not depend from bundler. It could easly extended to any bundler.
Different file iirc are cli and main entry.

**Comment by rehanvdm** [comment]
Cool, thanks for the info
