### ISSUE TITLE
Tooltip is outside of window

### ISSUE THREAD

**Issue by guillaumeduboc** [btd/esbuild-visualizer#8]
First, thanks a lot for this amazing library !! 
It is incredibly helpful to analyze the cause of a big bundle

in the following [stats.html.gz](https://github.com/btd/esbuild-visualizer/files/11602665/stats.html.gz), I am not able to read the package names because the tooltip is outside of the window

Can I create a PR to change the tooltips styles ?

**Comment by btd** [comment]
Hi, thanks for feedback and providing html file. I am welcoming PR, but can you first explain what you propose. I may be able to provide early feedback.

**Comment by guillaumeduboc** [comment]
The PR is ready as I did it locally

I thought of 2 things : 

1. remove the `whitespace: nowrap` for tooltips. If the path is too long, it will not fit in the browser
https://github.com/btd/esbuild-visualizer/blob/b28bc694b6f5391038366cfa543cdffc28d9068c/src/style/_base.scss#L63


2. make sure the tooltip doesn't start outside the window taking 0 if the value is negative
https://github.com/btd/esbuild-visualizer/blob/b28bc694b6f5391038366cfa543cdffc28d9068c/src/treemap/tooltip.tsx#L131-L139
